import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
import createDOMPurify from 'dompurify';
import JSZip from 'jszip';
const dom = new JSDOM('<!doctype html><html><body></body></html>');
globalThis.DOMParser = dom.window.DOMParser;
globalThis.NodeFilter = dom.window.NodeFilter;
globalThis.JSZip = JSZip;
globalThis.DOMPurify = createDOMPurify(dom.window);
import {parseDraft, convertBook, htmlBook} from '../dist/forge.js';
import {parseBook} from '../dist/parsers.js';

const draft = `# Chương 1: Bình minh
Đây là một ngày **tuyệt vời** để đọc sách.
> Học, học nữa, học mãi.

- Điểm một
- Điểm hai

# Chương 2: Hoàng hôn
Kết thúc một ngày với những trang viết *ý nghĩa*.
\`\`\`
code block
\`\`\`
`;

const blocks = parseDraft(draft, true);
assert.equal(blocks.length, 8);
assert.equal(blocks[0].type, 'h1');
assert.equal(blocks[0].text, 'Chương 1: Bình minh');

const bookObj = {
  title: 'Hành Trình Thử Nghiệm',
  author: 'Chang Tester',
  language: 'vi',
  markdown: true,
  blocks
};

// Test all formats
for (const fmt of ['epub', 'docx', 'fb2', 'html', 'rtf', 'txt']) {
  const blob = convertBook(bookObj, fmt);
  assert.ok(blob, `Format ${fmt} generated a blob`);
  assert.ok(blob.size > 0, `Format ${fmt} blob is not empty`);
  console.log(`PASS format ${fmt}: ${blob.size} bytes`);
}

// Test EPUB roundtrip: parsed by parseBook
const epubBlob = convertBook(bookObj, 'epub');
const file = new File([await epubBlob.arrayBuffer()], 'test-forge.epub', {type: 'application/epub+zip'});
const parsed = await parseBook(file);
assert.equal(parsed.book.title, 'Hành Trình Thử Nghiệm');
assert.equal(parsed.book.author, 'Chang Tester');
assert.ok(parsed.content.chapters.length >= 1);
console.log('PASS EPUB generated by BookForge can be opened & read by Chang Book Reader');

console.log('ALL FORGE TESTS PASSED!');
